spring.application.name=SpringEduManager
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:bootcamp
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
server.port=8080
# Security Configuration
SpringEduManager.security.admin.username=${APP_ADMIN_USER:admin@bootcamp.net}
SpringEduManager.security.admin.password=${APP_ADMIN_PASSWORD:admin2026}
SpringEduManager.security.user.username=${APP_USER_USER:alumno@bootcamp.net}
SpringEduManager.security.user.password=${APP_USER_PASSWORD:1234}
